# Generated by Django 3.2.4 on 2021-06-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_export_rate', models.CharField(max_length=150, null=True)),
                ('usa_import_rate', models.CharField(max_length=150, null=True)),
                ('eur_import_rate', models.CharField(max_length=150, null=True)),
                ('eur_export_rate', models.CharField(max_length=150, null=True)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_recorder.bank')),
            ],
            options={
                'verbose_name': 'Rates',
            },
        ),
    ]
