# Generated by Django 3.2.4 on 2021-06-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_recorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rates',
            old_name='bank_id',
            new_name='bank_name',
        ),
    ]
