# Generated by Django 3.2.4 on 2021-06-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_recorder', '0002_rename_bank_id_rates_bank_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rates',
            old_name='bank_name',
            new_name='bank_id',
        ),
    ]
