# Generated by Django 3.2.4 on 2021-06-19 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rate_recorder', '0004_rename_bank_id_rates_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
